
server:
  port: 8080

spring:
    application:
        name: authserver

    datasource:
      url : jdbc:mysql://localhost:3306/dapp?autoreconnect=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: password
      
      driver-class-name : com.mysql.cj.jdbc.Driver
      tomcat:
        test-while-idle: true
        validation-query: SELECT 1
      initialization-mode: never
      platform: mysql
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        ddl-auto: update

dapp:
  app:
    jwtSecret: dbAppSecretKey
    jwtExpirationMs: 86400000